#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="matrix-proxy"

if check_container_restarted ; then
    sanity_var HOMESERVER_URL "URL to your Matrix Homeserver"
    update_template /container/data/nginx/location/10-matrix_proxy.conf    \
                                                                    HOMESERVER_URL

    case "${HOMESERVER_TYPE,,}" in
        synapse )
            sed -i \
                        "s|{{HOMESERVER_TYPE}}|synapse|g" \
                    /container/data/nginx/location/10-matrix_proxy.conf

            render_template \
                                /container/data/nginx/matrix-proxy/homeserver-synapse.conf \
                                /container/data/nginx/location/11-homeserver-synapse.conf \
                            HOMESERVER_URL

            if var_true "${ENABLE_SYNAPSE_ADMIN}" ; then
                print_notice "Enabling Proxy to Synapse Admin"
                render_template \
                                    /container/data/nginx/matrix-proxy/synapse-admin.conf \
                                    /container/data/nginx/location/12-synapse-admin.conf \
                                HOMESERVER_URL

                sed -i "/deny all;/i\        allow 127.0.0.1;" /container/data/nginx/location/12-synapse-admin.conf
                allowed_synapse_admin=$(echo "SYNAPSE_ADMIN_ALLOWED_IPS" | tr "," "\n")
                for allowed_host in $allowed_synapse_admin; do
                    print_notice "[synapse_admin] Allowing ${allowed_host}"
                    sed -i "/allow 127.0.0.1/a\\        allow $allowed_host;" /container/data/nginx/location/12-synapse-admin.conf
                done

            fi
        ;;
    esac

    if var_true "${ENABLE_PROXY_MAS}" ; then
        print_notice "Enabling Proxy to Matrix Authentication Service"
        sanity_var MAS_URL "URL to your Media Repository"
        render_template \
                            /container/data/nginx/matrix-proxy/mas.conf \
                            /container/data/nginx/location/13-mas.conf \
                        MAS_URL
    fi

    if var_true "${ENABLE_PROXY_MEDIA_REPO}" ; then
        print_notice "Enabling Proxy to media repository"
        sanity_var MEDIA_REPO_URL "URL to your Media Repository"
        render_template \
                            /container/data/nginx/matrix-proxy/media-repo.conf \
                            /container/data/nginx/location/13-media-repo.conf \
                        MEDIA_REPO_URL
        if var_true "${MEDIA_REPO_PROXY_LOGOUT}" ; then
            print_notice "[media_repo] Intercepting Client Logout Requests and forwarding to media repo"
            render_template \
                                /container/data/nginx/matrix-proxy/media-repo_proxy-logout.conf \
                                /container/data/nginx/location/14-media-repo_proxy-logout.conf \
                            MEDIA_REPO_URL
        fi
    fi

    if var_true "${ENABLE_WELL_KNOWN}" ; then
        print_notice "Enabling .well-known serving"
        sanity_var WELL_KNOWN_CLIENT "Client information"
        sanity_var WELL_KNOWN_SERVER "Homeserver information"
        render_template \
                            /container/data/nginx/matrix-proxy/well-known.conf \
                            /container/data/nginx/location/15-well-known.conf \
                        WELL_KNOWN_CLIENT \
                        WELL_KNOWN_SERVER
    fi
fi

liftoff